language: php

php:
  - 7.0
  - 7.1
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - travis_wait composer install --prefer-source --no-interaction

script: vendor/bin/phpunit